import { MainHeader } from "@/components/main-header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useParams } from "next/navigation";
import ReactQueryProvider from "@/providers/react-query-provider";
import AuthProvider from "@/providers/auth-provider";
import { Toaster } from "@/components/ui/toaster";
import GoogleOauthProvider from "@/providers/google-oauth-provider";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className} suppressHydrationWarning={true}>
        <ReactQueryProvider>
          <GoogleOauthProvider>
            <AuthProvider>
              <Toaster />
              <MainHeader />
              {children}
            </AuthProvider>
          </GoogleOauthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
