import MainHeader from "@/components/main-header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useParams } from "next/navigation";
import ReactQueryProvider from "@/providers/react-query-provider";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ReactQueryProvider>
          <MainHeader />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
